CREATE CONSTRAINT product_id IF NOT EXISTS FOR (p:Product) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT store_id IF NOT EXISTS FOR (s:Store) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT shelf_id IF NOT EXISTS FOR (s:Shelf) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT customer_id IF NOT EXISTS FOR (c:Customer) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT orderitem_id IF NOT EXISTS FOR (oi:OrderItem) REQUIRE oi.id IS UNIQUE;
